apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "zeus.release_name" . }}
  labels:
    {{- include "zeus.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "zeus.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "zeus.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "zeus.serviceAccountName" . }}
      {{- with .Values.zeus.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            {{- toYaml .Values.service.ports | nindent 12 }}
          {{ - with .Values.zeus.containerSecurityContext }}
          securityContext:
            {{ - toYaml . | nindent 12 }}
          {{ - end }}
          {{- with .Values.zeus.livenessProbe }}
          livenessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zeus.readinessProbe }}
          readinessProbe:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.zeus.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
