services:
  backend-app:
    image: borisplaton/zeus:latest
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "${ZEUS_PORT}:${ZEUS_PORT}"
    env_file:
      - "${ENV_FILE}"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
        - action: rebuild
          path: pyproject.toml
        - action: sync+restart
          path: "${ENV_FILE}"
          target: /dev/null
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:7.0.34
    env_file:
      - "${ENV_FILE}"
    command: [ "--port", "${MONGO_PORT}" ]
    volumes:
      - mongodb:/data/db
    healthcheck:
      test: [
        "CMD", "mongosh",
        "--port", "${MONGO_PORT}",
        "-u", "${MONGO_INITDB_ROOT_USERNAME}",
        "-p", "${MONGO_INITDB_ROOT_PASSWORD}",
        "--authenticationDatabase", "admin",
        "--eval", "db.adminCommand('ping')"
      ]
      interval: 3s
      timeout: 2s
      retries: 5
      start_period: 2s

volumes:
  mongodb:
