# Displays available commands.
help:
    @just --list

# Initialize a project. Installs dependencies and pre-commit hooks.
init:
    uv python install 3.14
    uv venv --python 3.14 --clear
    source .venv/bin/activate && \
      uv sync && \
      pre-commit install
    echo "Project initialized. Dependencies, pre-commit hooks successfully installed."

# Check the project files and fixes them if it is possible.
format:
    ruff format
    ruff check --fix

# Start zeus and all corresponding services.
zeus-up env_file="envs/.env.local":
    ENV_FILE="{{ env_file }}" docker compose --env-file="{{ env_file }}" up --build --watch

# Stops zeus and all corresponding services.
zeus-down env_file="envs/.env.local":
    ENV_FILE="{{ env_file }}" docker compose --env-file="{{ env_file }}" down -t 5

# Enters zeus shell
zeus-sh env_file="envs/.env.local":
    ENV_FILE="{{ env_file }}" docker compose --env-file="{{ env_file }}" exec backend-app sh

run-migrations env_file="envs/.env.local":
    ENV_FILE="{{ env_file }}" docker compose --env-file="{{ env_file }}" exec backend-app python /app/src/inbound/cli migrate
