env_file := "./envs/.env.local"

set dotenv-path := env_file
set dotenv-load

# Display available commands.
help:
    @just --list

# Initialize a project. Installs dependencies and pre-commit hooks.
init:
    uv python install 3.14
    uv venv --python 3.14 --clear
    source .venv/bin/activate && \
      uv sync && \
      pre-commit install
    echo "Project initialized. Dependencies, pre-commit hooks successfully installed."

# Check the project files and fixes them if it is possible.
format:
    ruff format
    ruff check --fix

# Run all existing tests.
tests path = ".":
    pytest -vv {{ path }}

# Update snapshots for tests.
tests-snapshot-update:
    pytest --snapshot-update -vv

# Start zeus and all corresponding services.
[env("COMPOSE_ENV_FILES", env_file)]
[env("ENV_FILE", env_file)]
zeus-up:
    docker compose up --build --watch

# Stop zeus and all corresponding services.
[env("COMPOSE_ENV_FILES", env_file)]
[env("ENV_FILE", env_file)]
zeus-down:
    docker compose down -t 5

# Enter zeus shell.
[env("COMPOSE_ENV_FILES", env_file)]
[env("ENV_FILE", env_file)]
zeus-sh:
    docker compose exec backend-app sh

# Run all existing zeus migrations.
[env("COMPOSE_ENV_FILES", env_file)]
[env("ENV_FILE", env_file)]
migrate:
    docker compose exec backend-app python /app/src/inbound/cli migrate

# Connect to the running MongoDB instance.
[env("COMPOSE_ENV_FILES", env_file)]
[env("ENV_FILE", env_file)]
mongodb-connect:
    docker compose exec mongodb mongosh \
        --username "${MONGO_USERNAME}" \
        --password "${MONGO_PASSWORD}" \
        --host "${MONGO_HOST}" \
        --port "${MONGO_PORT}" \
        --authenticationDatabase admin \
        "${MONGO_DATABASE_NAME}"
